### ISSUE TITLE
root bug问题

### ISSUE THREAD

**Issue by 727327257** [dong031001/EnigTech2#13]
root  自带的书点开有崩溃问题

**Comment by dong031001** [comment]
`java.lang.NullPointerException
    at vazkii.patchouli.client.book.gui.GuiBookEntry.onFirstOpened(GuiBookEntry.java:55)
    at vazkii.patchouli.client.book.BookContents.openLexiconGui(BookContents.java:88)
    at vazkii.patchouli.client.book.gui.GuiBookEntry.displayOrBookmark(GuiBookEntry.java:215)
    at vazkii.patchouli.client.book.gui.GuiBookEntryList.actionPerformed(GuiBookEntryList.java:142)
    at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:443)
    at vazkii.patchouli.client.book.gui.GuiBook.mouseClicked(GuiBook.java:259)
    at vazkii.patchouli.client.book.gui.GuiBookEntryList.mouseClicked(GuiBookEntryList.java:114)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533)
    at vazkii.patchouli.client.book.gui.GuiBook.handleMouseInput(GuiBook.java:282)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)`
似乎是因为魔改配方导致的空指针问题

**Comment by dong031001** [comment]
由于没有进度，这本书其实并没有什么用，解决办法：禁用合成
